<a href="https://colab.research.google.com/github/Saifjafri212213/DS-mirai/blob/Saif-Jafri/Python_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,90,(5,5))
print(a)

b = a.mean(axis=1)
c = a.mean(axis=0)
print("Row mean :",b)
print("Columns mean",c)

i = np.where(a%2==0 , -1 , a)
print(i)

d = np.sort(a , axis=1)
print(d)

e = np.sort(a , axis=0)
print(e)

f = np.sum(a, axis=1)
print(f)

g = np.sum(a, axis=0)
print(g)

h = np.count_nonzero(i==-1 , axis=1)
print(h)






[[20 59 78  1 63]
 [76 21 18 37  3]
 [14 78 64 33 65]
 [ 6 79 89 86 24]
 [83 17 17 31 82]]
Row mean : [44.2 31.  50.8 56.8 46. ]
Columns mean [39.8 50.8 53.2 37.6 47.4]
[[-1 59 -1  1 63]
 [-1 21 -1 37  3]
 [-1 -1 -1 33 65]
 [-1 79 89 -1 -1]
 [83 17 17 31 -1]]
[[ 1 20 59 63 78]
 [ 3 18 21 37 76]
 [14 33 64 65 78]
 [ 6 24 79 86 89]
 [17 17 31 82 83]]
[[ 6 17 17  1  3]
 [14 21 18 31 24]
 [20 59 64 33 63]
 [76 78 78 37 65]
 [83 79 89 86 82]]
[221 155 254 284 230]
[199 254 266 188 237]
[2 2 3 3 1]


In [ ]:
stocks = np.random.randint(20,80,(5,5))
print(stocks)

demand = np.random.randint(20,80,(5,5))
print(demand)

remaining = stocks - demand
print(remaining)

c = np.where(remaining<0, 0, remaining)
print(c)

s = np.sum(remaining[remaining<0])
print(s*-1)

f = np.count_nonzero(remaining<0, axis=0)
print(f)

g = np.sort(remaining, axis=0)
print(g )




[[68 53 24 24 25]
 [49 34 37 70 77]
 [75 65 73 21 51]
 [77 49 59 57 55]
 [69 26 39 27 66]]
[[38 31 66 68 78]
 [27 55 63 78 48]
 [72 65 52 57 37]
 [52 58 34 31 65]
 [21 59 66 48 42]]
[[ 30  22 -42 -44 -53]
 [ 22 -21 -26  -8  29]
 [  3   0  21 -36  14]
 [ 25  -9  25  26 -10]
 [ 48 -33 -27 -21  24]]
[[30 22  0  0  0]
 [22  0  0  0 29]
 [ 3  0 21  0 14]
 [25  0 25 26  0]
 [48  0  0  0 24]]
330
[0 3 3 4 2]
[[  3 -33 -42 -44 -53]
 [ 22 -21 -27 -36 -10]
 [ 25  -9 -26 -21  14]
 [ 30   0  21  -8  24]
 [ 48  22  25  26  29]]


In [ ]:
import pandas as pd

file_ = pd.read_csv('student_data.csv', sep=',')

print(file_.head(8))
print(file_.tail(8))



   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
5                      0            