In [ ]:
import numpy as np

In [ ]:
a = np.array([1,4,5,3,9,3])
print(a)

np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

[1 4 5 3 9 3]
False
False


In [ ]:
a = np.zeros((3,3,2),dtype=int)
print(a)
print(type(a))
print(type(a[0]))

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
a = np.full(4,5, dtype=int)
print(a)

a = np.arange(7,41,3, dtype=int)
print(a)

a = np.linspace(2,20,6, dtype=int)
print(a)

[5 5 5 5]
[ 7 10 13 16 19 22 25 28 31 34 37 40]
[ 2  5  9 12 16 20]


In [ ]:
a = np.ones((3,5) , dtype=int)
print(a)
b = np.shape(a)
c = np.size(a)

print(c)
print(a.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
15
(3, 5)


In [ ]:
a = np.random.randint(2,45,4) #(start , end , no. of random number)
print(a)

b = np.random.choice([2,3,5,8] , 2) #
print(b)


[14 36  5 11]
[5 3]


In [ ]:
a = np.random.randint(5,28,5)
b = np.random.randint(4,100,6)
print(a)
print(b)
print(a*3)
# print(a-b)
# print(a+b)
print(a/b)

cc= [2,5,1,7]
d = [1,5,2,7,9]



[ 7 13  6 23 16]
[51 42 10 77 57 56]
[21 39 18 69 48]


ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [ ]:
a = np.random.randint(2,17,9)
print(a)

b = a.reshape((3,3))
print(b)

c = b.transpose()
print(c)

d = np.random.randint(2,9,6)
e = np.random.randint(2,12,6)
print(d)
print(e)

f = np.concatenate((d,e))
print(f)


[14  5  2  4  5 11 10 14 16]
[[14  5  2]
 [ 4  5 11]
 [10 14 16]]
[[14  4 10]
 [ 5  5 14]
 [ 2 11 16]]
[7 3 3 6 6 6]
[10  3 11 11 11  4]
[ 7  3  3  6  6  6 10  3 11 11 11  4]


In [ ]:
a = np.random.randint(2,20,6)
b = np.random.randint(5, 15,6)
print(a)
print(b)

# if b>a print b otherwise a will print
c = np.where(b>a ,b,a)
print(c)

[ 4 15 14 18 19  5]
[ 7  7 13  8 12  7]
[ 7 15 14 18 19  7]


In [ ]:
a = np.random.randint(2 ,10 ,6)
print(a)

b = np.sort(a)
print(b)

c = np.sum(a)
print(c)

d = np.mean(a)
print(d)

e = np.max(a)
print(e)

f = np.min(a)
print(f)

g = np.std(a)
print(g)

h = np.median(a)
print(h)

i = np.unique(a)
print(i)

[4 7 9 3 7 3]
[3 3 4 7 7 9]
33
5.5
9
3
2.29128784747792
5.5
[3 4 7 9]


In [ ]:
#a = np.random.randint(0, 150 ,10)
a=[]
for i in range(10):
    a.append(int(input()))
print(a)
a = np.array(a)

print(np.where(a>20 , "good inning","bad inning"))
print("lowest score = " , np.min(a))
print("Highest score = ",np.max(a))
print("Average = ",np.mean(a))
print(np.std(a))
print(np.median(a))


print("total run" , np.sum(a))


2
34
25
25
56
5
68
25
87
6
[2, 34, 25, 25, 56, 5, 68, 25, 87, 6]
['bad inning' 'good inning' 'good inning' 'good inning' 'good inning'
 'bad inning' 'good inning' 'good inning' 'good inning' 'bad inning']
lowest score =  2
Highest score =  87
Average =  33.3
27.085235830614433
25.0
total run 333


In [ ]:
import numpy as np

products = []
prices = []

n = int(input('enter no of product..'))

for i in range(n):
    product = input(f"Enter name of product {i+1}: ")
    price = float(input(f"Enter price of {product}: "))

    products.append(product)
    prices.append(price)

p = np.array(prices)

print("\nProducts and Prices:")
for i in range(n):
    print(products[i], ":", prices[i])

print("\nHighest Price:", p.max())
print("Lowest Price:", p.min())
print("Total Price:", p.sum())
print("Average Price:", p.mean())
print("Standard Deviation:", p.std())

enter no of product..3
Enter name of product 1: mobile
Enter price of mobile: 300
Enter name of product 2: tv
Enter price of tv: 400
Enter name of product 3: ac
Enter price of ac: 5000

Products and Prices:
mobile : 300.0
tv : 400.0
ac : 5000.0

Highest Price: 5000.0
Lowest Price: 300.0
Total Price: 5700.0
Average Price: 1900.0
Standard Deviation: 2192.4111536540463
